using ElixomClaim.Lib.Services;
using ElixomClaim.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ElixomClaim.Web.Controllers.Api;

[ApiController, Route("api/v1/payroll"), Authorize(Policy = "ApiAccess")]
public sealed class PayrollApiController(ISalaryPayrollService payroll, IActorResolver actors, ILogger<PayrollApiController> logger) : ControllerBase
{
    [HttpPost("preview")]
    public async Task<ActionResult<ApiPayrollPreview>> Preview([FromBody] ApiPayrollRequest request, CancellationToken ct)
    {
        var actor = await actors.ResolveActorAsync(HttpContext, "api:access", false, ct); if (!actor.IsSuccess) return Forbid();
        var result = await payroll.PreviewAsync(request.SalaryDefinitionId, actor.Value!.User.Id, request.AsOfDate, ct);
        if (result.IsFailure) return Problem(statusCode: 403, detail: result.Error);
        var value = result.Value!; return Ok(new ApiPayrollPreview(value.DueDate, value.Eligibility.ToString(), value.ProjectedTotal));
    }
    [HttpPost("run")]
    public async Task<ActionResult<ApiPayrollRun>> Run([FromBody] ApiPayrollRequest request, CancellationToken ct)
    {
        var actor = await actors.ResolveActorAsync(HttpContext, "api:access", false, ct); if (!actor.IsSuccess) return Forbid();
        var result = await payroll.GenerateForDefinitionAsync(request.SalaryDefinitionId, actor.Value!.User.Id, request.AsOfDate, ct);
        if (result.IsFailure) return Problem(statusCode: 409, detail: result.Error);
        logger.LogInformation("API payroll {PayrollId} generated by {ActorId}", result.Value!.Id, actor.Value.User.Id);
        return Ok(new ApiPayrollRun(result.Value.Id, result.Value.PeriodEndingDate, result.Value.PayrollTotal));
    }
}
public sealed record ApiPayrollRequest(Guid SalaryDefinitionId, DateOnly AsOfDate);
public sealed record ApiPayrollPreview(DateOnly DueDate, string Eligibility, decimal ProjectedTotal);
public sealed record ApiPayrollRun(Guid PayrollId, DateOnly PeriodEndingDate, decimal Total);
