using ElixomClaim.Lib.Services;
using ElixomClaim.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ElixomClaim.Web.Controllers.Api;

[ApiController, Route("api/v1/payroll"), Authorize(Policy = "ApiAccess")]
public sealed class PayrollApiController(ISalaryPayrollService payroll, IOperationRecordService operations, IActorResolver actors, ILogger<PayrollApiController> logger) : ControllerBase
{
    [HttpPost("preview")]
    public async Task<ActionResult<ApiPayrollPreview>> Preview([FromBody] ApiPayrollRequest request, CancellationToken ct)
    {
        var actor = await actors.ResolveActorAsync(HttpContext, "api:access", false, ct); if (!actor.IsSuccess) return Forbid();
        var result = await payroll.PreviewAsync(request.SalaryDefinitionId, actor.Value!.User.Id, request.AsOfDate, ct);
        if (result.IsFailure) return Problem(statusCode: 403, detail: result.Error);
        var value = result.Value!; return Ok(new ApiPayrollPreview(value.DueDate, value.Eligibility.ToString(), value.ProjectedTotal));
    }
    [HttpPost("run")]
    public async Task<ActionResult<ApiPayrollRun>> Run([FromBody] ApiPayrollRequest request, CancellationToken ct)
    {
        var actor = await actors.ResolveActorAsync(HttpContext, "api:access", false, ct); if (!actor.IsSuccess) return Forbid();
        var key = Request.Headers["Idempotency-Key"].FirstOrDefault() ?? Request.Headers["X-Idempotency-Key"].FirstOrDefault();
        if (string.IsNullOrWhiteSpace(key)) return Problem(statusCode: 400, detail: "An Idempotency-Key header is required.");
        var reservation = await operations.ReserveAsync($"api:payroll-run:{actor.Value!.User.Id:N}:{key.Trim()}", "PayrollRun", actor.Value.User.Id.ToString(), ct);
        if (!reservation.IsNew) return Accepted(new { operation = reservation.Record.IdempotencyKey, status = reservation.Record.Status });
        var result = await payroll.GenerateForDefinitionAsync(request.SalaryDefinitionId, actor.Value!.User.Id, request.AsOfDate, ct);
        if (result.IsFailure)
        {
            await operations.UpdateStatusAsync(reservation.Record.Id, "Failed", result.Error, ct);
            return Problem(statusCode: 409, detail: result.Error);
        }
        await operations.UpdateStatusAsync(reservation.Record.Id, "Completed", $"Payroll:{result.Value!.Id}", ct);
        logger.LogInformation("API payroll {PayrollId} generated by {ActorId}", result.Value!.Id, actor.Value.User.Id);
        return Ok(new ApiPayrollRun(result.Value.Id, result.Value.PeriodEndingDate, result.Value.PayrollTotal));
    }
}
public sealed record ApiPayrollRequest(Guid SalaryDefinitionId, DateOnly AsOfDate);
public sealed record ApiPayrollPreview(DateOnly DueDate, string Eligibility, decimal ProjectedTotal);
public sealed record ApiPayrollRun(Guid PayrollId, DateOnly PeriodEndingDate, decimal Total);
