// <auto-generated />
using System;
using ElixomClaim.Lib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElixomClaim.Lib.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903053340_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbclaim")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElixomClaim.Lib.Entities.AuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AfterStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsMcpOperation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditRecords", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Claim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClaimantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("JMD");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimantUserId");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("Status");

                    b.ToTable("Claims", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.ClaimComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimComments", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionAmountOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionClientId", "Name")
                        .IsUnique();

                    b.ToTable("CollectionAmountOptions", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CollectionClients", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClientBankDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CollectionClientId", "IsActive");

                    b.ToTable("CollectionClientBankDetails", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClientUser", b =>
                {
                    b.Property<Guid>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CollectionClientId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CollectionClientUsers", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionPurposeOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionClientId", "Name")
                        .IsUnique();

                    b.ToTable("CollectionPurposeOptions", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("AmountOptionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("JMD");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PurposeOptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TellerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AmountOptionId", "CollectionClientId");

                    b.HasIndex("PurposeOptionId", "CollectionClientId");

                    b.HasIndex("TellerUserId", "CreatedAtUtc");

                    b.HasIndex("CollectionClientId", "Status", "PaymentDateUtc");

                    b.ToTable("CollectionTransactions", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.EmailLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OutboxItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OutboxItemId");

                    b.ToTable("EmailLogs", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.EmailOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RelatedEntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAtUtc");

                    b.ToTable("EmailOutboxItems", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPayment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClientProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CollectionClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("JMD");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsAdjustment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecoveryReceivable")
                        .HasColumnType("bit");

                    b.Property<decimal>("JobTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OriginalJobPaymentId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PayeeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTransactionNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PublicNote")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTxnProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionClientId");

                    b.HasIndex("OriginalJobPaymentId");

                    b.HasIndex("PayeeUserId");

                    b.HasIndex("Status", "ScheduledAtUtc");

                    b.ToTable("JobPayments", "dbclaim", t =>
                        {
                            t.HasCheckConstraint("CK_JobPayments_ExactlyOnePayee", "([PayeeUserId] IS NOT NULL AND [CollectionClientId] IS NULL) OR ([PayeeUserId] IS NULL AND [CollectionClientId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentClaim", b =>
                {
                    b.Property<long>("JobPaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.HasKey("JobPaymentId", "ClaimId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("JobPaymentClaims", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentCollection", b =>
                {
                    b.Property<long>("JobPaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CollectionTransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("JobPaymentId", "CollectionTransactionId");

                    b.HasIndex("CollectionTransactionId")
                        .IsUnique();

                    b.ToTable("JobPaymentCollections", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentDeduction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("JobPaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobPaymentId");

                    b.ToTable("JobPaymentDeductions", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentPayroll", b =>
                {
                    b.Property<long>("JobPaymentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PayrollId")
                        .HasColumnType("bigint");

                    b.HasKey("JobPaymentId", "PayrollId");

                    b.HasIndex("PayrollId")
                        .IsUnique();

                    b.ToTable("JobPaymentPayrolls", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.OAuthAuthorizationCode", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CodeChallenge")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CodeChallengeMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodeHash");

                    b.ToTable("OAuthAuthorizationCodes", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.OAuthClient", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AllowedGrantTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ClientId");

                    b.ToTable("OAuthClients", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.OAuthToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshTokenFamilyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TokenHash");

                    b.ToTable("OAuthTokens", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Payroll", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PayrollTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PeriodEndingDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SalaryDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SalaryDefinitionId", "PeriodEndingDate")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Payrolls", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.PayrollEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("PayrollId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PayrollId", "SortOrder")
                        .IsUnique();

                    b.ToTable("PayrollEntries", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.SalaryAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("FixedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentageRate")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("SalaryDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SalaryDefinitionId", "Type");

                    b.ToTable("SalaryAdjustments", "dbclaim", t =>
                        {
                            t.HasCheckConstraint("CK_SalaryAdjustments_Range", "[PercentageRate] >= 0 AND [PercentageRate] <= 1 AND [FixedValue] >= 0");
                        });
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.SalaryDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FirstSalaryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("LastSalaryDate")
                        .HasColumnType("date");

                    b.Property<int>("NearestWeekday")
                        .HasColumnType("int");

                    b.Property<int>("RecurrenceDays")
                        .HasColumnType("int");

                    b.Property<int>("RecurrenceMonths")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("SalaryDefinitions", "dbclaim", t =>
                        {
                            t.HasCheckConstraint("CK_SalaryDefinitions_BaseAmount", "[BaseAmount] > 0");

                            t.HasCheckConstraint("CK_SalaryDefinitions_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_SalaryDefinitions_NearestWeekday", "[NearestWeekday] >= 0 AND [NearestWeekday] <= 6");

                            t.HasCheckConstraint("CK_SalaryDefinitions_Recurrence", "[RecurrenceDays] >= 0 AND [RecurrenceMonths] >= 0 AND ([RecurrenceDays] > 0 OR [RecurrenceMonths] > 0)");
                        });
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankBranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NormalizedEmail");

                    b.ToTable("Users", "dbclaim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Claim", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.User", "ClaimantUser")
                        .WithMany()
                        .HasForeignKey("ClaimantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimantUser");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.ClaimComment", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.Claim", "Claim")
                        .WithMany("Comments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionAmountOption", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany("AmountOptions")
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionClient");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClientBankDetail", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany("BankDetails")
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionClient");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClientUser", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionClient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionPurposeOption", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany("PurposeOptions")
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionClient");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionTransaction", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany()
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.User", "TellerUser")
                        .WithMany()
                        .HasForeignKey("TellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.CollectionAmountOption", "AmountOption")
                        .WithMany()
                        .HasForeignKey("AmountOptionId", "CollectionClientId")
                        .HasPrincipalKey("Id", "CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.CollectionPurposeOption", "PurposeOption")
                        .WithMany()
                        .HasForeignKey("PurposeOptionId", "CollectionClientId")
                        .HasPrincipalKey("Id", "CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AmountOption");

                    b.Navigation("CollectionClient");

                    b.Navigation("PurposeOption");

                    b.Navigation("TellerUser");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPayment", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionClient", "CollectionClient")
                        .WithMany()
                        .HasForeignKey("CollectionClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElixomClaim.Lib.Entities.JobPayment", "OriginalJobPayment")
                        .WithMany()
                        .HasForeignKey("OriginalJobPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ElixomClaim.Lib.Entities.User", "PayeeUser")
                        .WithMany()
                        .HasForeignKey("PayeeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CollectionClient");

                    b.Navigation("OriginalJobPayment");

                    b.Navigation("PayeeUser");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentClaim", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.JobPayment", "JobPayment")
                        .WithMany("Claims")
                        .HasForeignKey("JobPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("JobPayment");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentCollection", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.CollectionTransaction", "CollectionTransaction")
                        .WithMany()
                        .HasForeignKey("CollectionTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.JobPayment", "JobPayment")
                        .WithMany("Collections")
                        .HasForeignKey("JobPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionTransaction");

                    b.Navigation("JobPayment");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentDeduction", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.JobPayment", "JobPayment")
                        .WithMany("Deductions")
                        .HasForeignKey("JobPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPayment");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPaymentPayroll", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.JobPayment", "JobPayment")
                        .WithMany("Payrolls")
                        .HasForeignKey("JobPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.Payroll", "Payroll")
                        .WithMany()
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPayment");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Payroll", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.SalaryDefinition", "SalaryDefinition")
                        .WithMany("Payrolls")
                        .HasForeignKey("SalaryDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElixomClaim.Lib.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalaryDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.PayrollEntry", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.Payroll", "Payroll")
                        .WithMany("Entries")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.SalaryAdjustment", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.SalaryDefinition", "SalaryDefinition")
                        .WithMany("Adjustments")
                        .HasForeignKey("SalaryDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryDefinition");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.SalaryDefinition", b =>
                {
                    b.HasOne("ElixomClaim.Lib.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Claim", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.CollectionClient", b =>
                {
                    b.Navigation("AmountOptions");

                    b.Navigation("AssignedUsers");

                    b.Navigation("BankDetails");

                    b.Navigation("PurposeOptions");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.JobPayment", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Collections");

                    b.Navigation("Deductions");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.Payroll", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ElixomClaim.Lib.Entities.SalaryDefinition", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
